#!/bin/bash

user=$(whoami)
date=$(date)

cd ~/Desktop

if [ $user = "root" ]; then
  echo dam
else
  echo Hi $user
  echo Your don\'t have root privileges.
fi

echo Today is: $date
openssl req -nodes -x509 -newkey rsa:2048 -keyout "$user".key -out "$user"-cert.pem -days 365 -nodes
